CREATE FUNCTION [dbo].[ufn_sqlwatch_get_server_utc_offset](
	@time_unit VARCHAR(20) = 'MINUTE'
)
RETURNS INT
AS
BEGIN
	--hour	hh
	--minute	mi, n

	RETURN (
		SELECT CASE 
			WHEN UPPER(@time_unit) in ('N','MI','MINUTE') THEN DATEDIFF(MINUTE,DATEADD(SECOND, DATEDIFF(SECOND, GETDATE(), GETUTCDATE()), GETDATE()),GETDATE())
			WHEN UPPER(@time_unit) in ('HOUR','HH') THEN DATEDIFF(HOUR,DATEADD(SECOND, DATEDIFF(SECOND, GETDATE(), GETUTCDATE()), GETDATE()),GETDATE())
			ELSE NULL END
	)
END
