{
 "title": "Checks",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Status",
    "label": "Status",
    "query": "OK,WARNING,CRITICAL,CHECK ERROR"
   },
   {
    "name": "Check",
    "label": "Check",
    "query": "select check_name from [dbo].[vw_sqlwatch_report_dim_check] where sql_instance = '$sql_instance'"
   }
  ]
 },
 "panels": [
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'OK'"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'WARNING'"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] <> 'OK'\n  AND [last_check_status] <> 'WARNING'"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'CHECK ERROR'"
    }
   ]
  },
  {
   "title": "$Check Description",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n      [time]=GETUTCDATE() \n      ,metric = check_description\n      ,[value] = 1\n  FROM [dbo].[vw_sqlwatch_report_dim_check]\n  WHERE 1=1 --$__timeFilter(snapshot_time)\n  and check_name = '$Check'\n  AND [sql_instance] = '$sql_instance'\n  \n  "
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT  [check_name] = [check_name]\n        ,[last_check_value] = convert(varchar(max),[last_check_value])\n        ,status = CASE [last_check_status] \n        WHEN 'CRITICAL' THEN 2\n        WHEN 'WARNING' THEN 1\n        WHEN 'OK' THEN 0\n        ELSE 3 END\n  FROM [dbo].[vw_sqlwatch_report_dim_check] with (nolock)\n  WHERE  [sql_instance] = '$sql_instance'\n  and [last_check_status] in ($Status)\n  order by case when last_check_status = 'OK' then dateadd(month,-1,last_check_date_local) else last_check_date_local end desc"
    }
   ]
  },
  {
   "title": "$Check Status History",
   "type": "heatmap",
   "description": "The colours are a bit off but this is just this panel's and Grafana's limitation. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], 1s)\n      ,[OK] = case [check_status] when 'OK' then 1 else 0 end\n      ,[WARNING] = case [check_status] when 'WARNING' then 2 else 0 end\n      ,[CRITICAL] = case [check_status] when 'CRITICAL' then 3 else 0 end\n      ,[ERROR] = case [check_status] when 'CHECK ERROR' then 4 else 0 end\n      --,[OTHER] = case when [check_status] not in ('OK','WARNING','CRITICAL','CHECK ERROR') then 5 else 0 end\n  FROM [dbo].[vw_sqlwatch_report_fact_check]\n  WHERE $__timeFilter(snapshot_time)\n  and check_name = '$Check'\n  AND [sql_instance] = '$sql_instance'\nORDER BY\n  time ASC\n  "
    }
   ]
  },
  {
   "title": "$Check Value History",
   "type": "graph",
   "description": "The colours are a bit off but this is just this panel's and Grafana's limitation. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], 1s)\n      ,[check_value]\n  FROM [dbo].[vw_sqlwatch_report_fact_check]\n  WHERE $__timeFilter(snapshot_time)\n  and check_name = '$Check'\n  AND [sql_instance] = '$sql_instance'\nORDER BY\n  time ASC\n  "
    }
   ]
  },
  {
   "title": "$Check Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], 1s),\n      [ms] = check_exec_time_ms\n  FROM [dbo].[vw_sqlwatch_report_fact_check]\n  WHERE $__timeFilter(snapshot_time)\n  and check_name = '$Check'\n  AND [sql_instance] = '$sql_instance'\nORDER BY\n  time ASC\n  "
    }
   ]
  }
 ]
}