{
 "title": "Instance Overview",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Waits", "label": "Waits By", "query": "Category,Type" },
   { "name": "WaitCalc", "label": "Wait Calculation", "query": "ms/sec,Delta" },
   { "name": "ShowChecksOK", "label": "Show OK Checks", "query": "Yes,No" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "<br><h1 id=\"overview\">Overview</h1>\r\n<p>This dashboard was designed to help you understand what happens in your SQL Server and help you find bottlenecks. A single page view helps correlate various events and makes it easier to spot trends.<br>\r\nLike most computer systems, SQL Server relies on the following components to perform well: <b>CPU > Memory > Storage > Network</b>.\r\nIf any of these does not perform well, we may be seeing performance degradation in our database and/or application.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "description": "<p>For these links to work on Grafana 6.0 and above, the HTML sanitisation must be switched off in grafana.ini. This is because since version 6.5 Grafana removes any custom CSS, IDs and Classes from HTML panels and HTML Anchors works using IDs. <a href=\"https://grafana.com/docs/grafana/latest/administration/configuration/#disable_sanitize_html\">Read more</a></p>",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<br>\n<div style=\"position:fixed;\">\n\t<ul>\n\t\t<li><a href=\"/d/sqlwatch-repository-summary/summary?orgId=1&refresh=15s\">Servers Summary</a></li>\n\t</ul>\n\t<ul>\n\t\t<li><a href=\"#overview\">Overview</a></li>\n\t\t<li><a href=\"#workload\">Workload</a></li>\n\t\t\t<ul>\n\t\t\t\t<li><a href=\"#cpu\">CPU</a></li>\n\t\t\t\t<li><a href=\"#activity\">Activity</a></li>\n\t\t\t\t<li><a href=\"#compilations\">Compilations</a></li>\n\t\t\t\t<li><a href=\"#wait\">Wait Times</a></li>\n\t\t\t\t<li><a href=\"#scheduler\">Scheduler Tasks</a></li>\n\t\t\t\t<li><a href=\"#long\">Long Queries</a></li>\n\t\t\t\t<li><a href=\"#errors\">Errors</a></li>\n\t\t\t\t\n\t\t\t</ul>\n\t\t<li><a href=\"#locking\">Locking</a></li>\n\t\t<li><a href=\"#memory\">Memory</a></li>\n\t\t<li><a href=\"#tempdb\">TempDB</a></li>\n\t\t<li><a href=\"#storage\">Storage</a></li>\n\t\t<li><a href=\"#disks\">OS Disks</a></li>\n\t\t<li><a href=\"#network\">OS Network</a></li>\n\t</ul>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup(pc.[snapshot_time], $aggregation)\n      ,[value] = AVG(pc.[cntr_value_calculated])\n  FROM [dbo].[sqlwatch_logger_perf_os_performance_counters] pc\n\t\tinner join [dbo].[sqlwatch_meta_performance_counter] mpc\n\t\t\ton pc.sql_instance = mpc.sql_instance\n\t\t\tand pc.performance_counter_id = mpc.performance_counter_id  \n  WHERE $__timeFilter(pc.snapshot_time)\n  AND mpc.counter_name = 'Processor Time %'\n  AND pc.[sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup(pc.[snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "  Runnable",
   "type": "bargauge",
   "description": "Tasks that are ready to be run but cannot be run due to lack of resources.",
   "gridPos": { "h": 8, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Runnable Tasks] = MAX([runnable_tasks_count])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_schedulers]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with cte_blocking_chains as (\r\n\tSELECT  [attach_activity_id], [attach_activity_sequence], [blocking_start_time], [blocking_end_time], [blocked_ecid], [blocked_spid], [blocked_sql], [database_name]\r\n\t, [lock_mode], [blocking_ecid], [blocking_spid], [blocking_sql], [blocking_duration_ms], [blocking_client_app_name], [blocking_client_hostname]\r\n\t, [report_xml], [snapshot_time], [snapshot_type_id], [sql_instance]\r\n\t\t, blocking_chain_no = row_number() over (partition by blocking_spid, blocked_spid, convert(datetime2(0),blocking_start_time) order by blocking_duration_ms desc)\r\n\tFROM [dbo].[sqlwatch_logger_xes_blockers]\r\n\t)\r\nselect [Blocked Processes]=count(distinct blocked_spid)\r\n      ,[time]=report_time\r\nfrom dbo.sqlwatch_logger_snapshot_header h\r\n  \tleft join cte_blocking_chains d\r\n\t\ton  h.snapshot_time = d.[snapshot_time]\r\n\t\tand h.snapshot_type_id = d.snapshot_type_id\r\n\t\tand h.sql_instance = d.sql_instance\r\n\t\tand blocking_chain_no = 1\r\n  WHERE $__timeFilter(h.snapshot_time)\r\n   AND h.[sql_instance] = '$sql_instance'\r\ngroup by  report_time\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "  Wait time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = [report_time] --$__timeGroup([report_time], $aggregation) \n      ,metric = 'Wait Time'\n      ,[value] = sum([wait_time_ms_per_second])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_wait_stats]\n  WHERE 1=1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [report_time] --$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": " Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[value] = AVG([physical_memory_in_use_kb]*1.0/([physical_memory_in_use_kb]+[available_commit_limit_kb]))\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_process_memory]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Latency] = MAX([io_latency_read])+MAX([io_latency_write])\n      ,[Disk] = left([file_physical_name],2)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) , left([file_physical_name],2)\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Reads] = SUM([bytes_read_per_second])\n      ,[Disk Reads] = left([file_physical_name],2)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) ,left([file_physical_name],2)\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Writes] = SUM([bytes_written_per_second])\n      ,[Disk Writes] = left([file_physical_name],2)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) , left([file_physical_name],2)\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'OK'\n  AND check_enabled = 1"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'WARNING'\n  AND check_enabled = 1"
    }
   ]
  },
  {
   "title": "CRITICAL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] <> 'OK'\n  AND [last_check_status] <> 'WARNING'\n  AND check_enabled = 1"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT value=count(*)\n  FROM [dbo].[sqlwatch_meta_check]\n  WHERE [sql_instance] = '$sql_instance'\n  AND [last_check_status] = 'CHECK ERROR'\n  AND check_enabled = 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT [time]=getdate()\r\n      ,[data] = ' Physical Machine Name: ' + [physical_name] + char(10) + char(13) + ' Service Name: ' + service_name + case when [service_name] = 'MSSQLSERVER' then ' (Default Instance)' else '' end + char(10) + char(13) + ' IP Address: ' + [local_net_address] + ',' + convert(varchar(max),[local_tcp_port]) + \r\n      +char(10) + char(13) + ' SQL Version: ' + [sql_version]\r\n  FROM [dbo].[sqlwatch_meta_server]\r\n  WHERE servername = '$sql_instance'"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 21 },
   "options": {
    "content": "<br><br><br><h1 id=\"workload\">SQL Server Activity and Workload</h1>\r\n\r\n<br><h2 id=\"cpu\">CPU</h2>\r\n<p>The CPU chart is split into System (OS) and SQL Server. In an ideal scenario, all of the utilistaison should be allocated to SQL Server and only very small amount to system. SQL Server is also licensed per core, the more CPU cores the most expensive the license. You do not want to be paying a lot of money and not use it.\r\n<a href=\"/d/sqlwatch-long-queries/long-queries?${__url_time_range}&var-DataSource=${DataSource}&var-sql_instance=${sql_instance}\">See Long Queries captured during this period</a>\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processor Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup(pc.[snapshot_time], $aggregation)\n      ,metric = pc.[instance_name]\n      ,[value] = AVG(pc.[cntr_value_calculated])\n  FROM [dbo].[sqlwatch_logger_perf_os_performance_counters] pc\n\t\tinner join [dbo].[sqlwatch_meta_performance_counter] mpc\n\t\t\ton pc.sql_instance = mpc.sql_instance\n\t\t\tand pc.performance_counter_id = mpc.performance_counter_id  \n  WHERE $__timeFilter(pc.snapshot_time)\n  AND mpc.counter_name = 'Processor Time %'\n  AND pc.[sql_instance] = '$sql_instance'\n  GROUP BY pc.[instance_name]\n      ,$__timeGroup(pc.[snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation)\n      ,[min] = min([cntr_value_calculated])\n      ,[max] = max([cntr_value_calculated])\n  FROM (\n    select snapshot_time, [cntr_value_calculated]=sum([cntr_value_calculated])\n    from [dbo].[sqlwatch_logger_perf_os_performance_counters] pc\n\t\tinner join [dbo].[sqlwatch_meta_performance_counter] mpc\n\t\t\ton pc.sql_instance = mpc.sql_instance\n\t\t\tand pc.performance_counter_id = mpc.performance_counter_id      \n    WHERE $__timeFilter(pc.snapshot_time)\n  AND mpc.counter_name = 'Processor Time %'\n  AND pc.[sql_instance] = '$sql_instance'    \n    group by snapshot_time\n  ) t\n  GROUP BY $__timeGroup([snapshot_time], $aggregation)\nORDER BY\n  time ASC\n\n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 33 },
   "options": {
    "content": "<br><br><h2 id=\"activity\">Activity</h2>\r\n<p><b>Batch Requests/sec</b>: The number of batch requests received per second and is a good general indicator for the activity level of the SQL Server. This counter is highly dependent on the hardware and quality of code running on the server. The more powerful the hardware, the higher this number can be, even on poorly coded applications. A value of 1000 batch requests/sec is easily attainable, though a typical 100Mbs NIC can only handle about 3000 batch requests/sec. Many other counter thresholds depend upon batch requests/sec while, in some cases, a low (or high) number does not point to poor processing power. You should frequently use this counter in combination with other counters, such as processor utilization or user connections. In version 2000, \"Transactions/ sec\" was the counter most often used to measure overall activity, while versions 2005 and later use \"Batch Requests/sec\". Versions 2005 before SP2, measure this counter differently and may lead to some misunderstandings. Read the footnote for more details.</p>\r\n\r\n<p><b>SQL Compilations/sec</b>: Number of times that Transact-SQL compilations occurred, per second (including recompiles). The lower this value is the better. High values often indicate excessive ad-hoc querying and should be as low as possible. If excessive ad-hoc querying is happening, try rewriting the queries as procedures or invoke the queries using sp_executeSQL. When rewriting isn’t possible, consider using a plan guide or setting the database to parameterization forced mode.</p>\r\n\r\n<p><b>SQL Re-Compilations/sec</b>: The number of times, per second, that Transact-SQL objects attempted to be executed but had to be recompiled before completion. This number should be at or near zero since recompiles can cause deadlocks and exclusive compile locks. This counter’s value should follow in proportion to \"Batch Requests/sec\" and \"SQL Compilations/ sec\". This needs to be nil in your system as much as possible.</p>\r\n\r\n<p><b>Logins/sec</b>: *You want < 2* The number of user logins per second. Any value over 2 may indicate insufficient connection pooling.</p>\r\n\r\n<p><b>User Connections</b>: The number of users currently connected to the SQL Server. This counter should roughly track with \"Batch Requests/Sec\". They should generally rise and fall together. For example, blocking problems could be revealed by rising user connections, lock waits and lock wait time coupled with declining batch requests/sec.</p>\r\n\r\n<p><b>Transactions/sec</b>: Number of transactions started for the database per second.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Batch Requests/sec','Logins/sec','Transactions/sec','User Connections','SQL Compilations/sec','SQL Re-Compilations/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation)\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Database Transactions /sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Transactions/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 56 },
   "options": {
    "content": "<br><br><h2 id=\"compilations\">SQL Compilations</h2>\r\n\r\n<p><b>SQL Compilations/sec</b>:  You want it to be < 10% (of the number of Batch Requests/Sec). Number of times that Transact-SQL compilations occurred, per second (including recompiles). The lower this value is the better. High values often indicate excessive ad-hoc querying and should be as low as possible. If excessive ad-hoc querying is happening, try rewriting the queries as procedures or invoke the queries using sp_executeSQL. When rewriting isn’t possible, consider using a plan guide or setting the database to parameterization forced mode.</p>\r\n\r\n<p><b>SQL Re-Compilations/sec</b>: You want it to be < 10% (of the number of SQL Compilations/sec). The number of times, per second, that Transact-SQL objects attempted to be executed but had to be recompiled before completion. This number should be at or near zero since recompiles can cause deadlocks and exclusive compile locks. This counter’s value should follow in proportion to \"Batch Requests/sec\" and \"SQL Compilations/ sec\". This needs to be nil in your system as much as possible.</p>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compilation Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('SQL Compilations/sec','SQL Re-Compilations/sec','Batch Requests/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 68 },
   "options": {
    "content": "<br><br><h2 id=\"wait\">Wait Times</h2>\r\n\r\n<p>If a particular resource is not available, SQL Server will have to wait before it can process the query. For example, if the storage is too slow, SQL Server will have to wait for the disk \"to deliver\" the data. Analogically, if the CPU is too busy, SQL Server will have to wait for it to become available.\r\nAll this means, that if SQL is waiting too much, our queries do not get executed straight away but are put in a queue which makes the system feel slow. This chart is critical in understanding what SQL Server is waiting on. The SQLSkills website is a great resource to learn about waits: <a href=\"https://www.sqlskills.com/help/waits/\">https://www.sqlskills.com/help/waits/</a></p> \r\n<p>You can change how the wait types are grouped, either by Type or Category, using the filter on top or link in the chart.</p>\r\n<p><a href=\"/d/sqlwatch-wait-events/wait-events?${__url_time_range}&var-DataSource=${DataSource}&var-sql_instance=${sql_instance}\">See captured queries and transactions that have contributed to the wait.</a></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wait Time $WaitCalc by Wait $Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,[value] = case when '$WaitCalc' = 'ms/sec' then avg([wait_time_ms_per_second]) else avg(wait_time_ms_delta) end\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_wait_stats]\n  WHERE 1=1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 82 },
   "options": {
    "content": "\t<br><br><h2 id=\"scheduler\">Scheduler Tasks</h2>\r\n\t<p>SQL Server has its own, internal task mechanism controlled by the SQLOS. Every time we run a query, SQL Server will invoke one or more tasks to run this task, get data from tables etc. SQL Server has one scheduler per CPU thread.<br>\r\n\t<b>Runnable tasks:</b> Number of workers, with tasks assigned to them, that are waiting to be scheduled on the runnable queue. If this number is high, it may indicate CPU pressure.</p>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler Tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Runnable Tasks] = MAX([runnable_tasks_count])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_schedulers]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Current Tasks] = MAX([current_tasks_count])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_schedulers]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 91 },
   "options": {
    "content": "<br><br><h2 id=\"long\">Long Queries</h2>\r\n<p>Long running queries are usually caused by poor queries, trying to process too much data at a time clogging CPU, Memory and oversaturating storage. However, some long running processes are OK, for example sleeping tasks or background processes that do not eaty too much resources.\r\nIf you have a long running query that you are OK with, you can exclude it from collection in <span style=\"font-family:monospace;font-size:12px;background:#3D3D3D;padding:2px 4px 2px 4px;border-radius:2px;\">[dbo].[sqlwatch_config_exclude_xes_long_query]</span></p>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Long Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT [time] = report_time\r\n      , [Long Sessions]=count(distinct [session_id])\r\n \r\n  FROM dbo.sqlwatch_logger_snapshot_header h\r\n    left join [dbo].[sqlwatch_logger_xes_long_queries] d\r\n\t\ton  h.snapshot_time = d.[snapshot_time]\r\n\t\tand h.snapshot_type_id = d.snapshot_type_id\r\n\t\tand h.sql_instance = d.sql_instance\r\n  WHERE h.snapshot_type_id = 7\r\n   AND h.[sql_instance] = '$sql_instance'\r\n   AND $__timeFilter(h.snapshot_time)\r\n   group by report_time\r\nORDER BY\r\n  report_time desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 100 },
   "options": {
    "content": "<br><br><h2 id=\"errors\">Errors</h2>\r\n<p>Errors reported by SQL engine, excludes \"User Errors\" and \"Info Errors\". These will likely be relatively serious, such a broken connections, kill connections, database offline errors.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Errors/sec')\n  AND [sql_instance] = '$sql_instance'\n  AND [instance_name] not in ('User Errors','Info Errors','_Total')\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 109 },
   "options": {
    "content": "<br><br><h1 id=\"locking\">SQL Server Locking</h1>\r\n<p>Locking mechanism is critical part of every relational database. Every time a row is read, inserted or modified SQL Server applies appropriate locks to ensure no one else can access the data whilst it's being read of modified. The locking mechanism ensures data consistency however, excessive locking can lead overal poor performance and even create blocking chains.</p>\r\n<br>\r\n<p><b>Lock Requests / sec</b>: *You want <1000*.  The number of new locks and locks converted per second. This metric’s value should generally correspond to \"Batch Requests/sec\". Values > 1000 may indicate queries are accessing very large numbers of rows and may benefit from tuning.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock Requests/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Lock Requests/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 120 },
   "options": {
    "content": "<br><p><b>Lock Timeouts/ sec</b>: *You want <1*.  Shows the number of lock requests per second that timed out, including internal requests for NOWAIT locks. A value greater than zero might indicate that user queries are not completing. The lower this value is, the better.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock Timeouts/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Lock Timeouts/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 128 },
   "options": {
    "content": "<br>\r\n<p><b>Lock Waits/sec</b>: *You want 0*.  How many times users waited to acquire a lock over the past second. Values greater than zero indicate at least some blocking is occurring, while a value of zero can quickly eliminate blocking as a potential root-cause problem. As with \"Lock Wait Time\", lock waits are not recorded by PerfMon until after the lock event completes.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lock Waits/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Lock Waits/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 136 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>Avg Wait Time (ms)</b>: *You want <500 *   \r\nThe average wait time, in milliseconds, for each lock request that had to wait. Average wait time longer than 500ms may indicate excessive blocking. This value should generally correlate to \"Lock Waits/sec\" and move up or down with it accordingly.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Wait Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Average Wait Time (ms)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 144 },
   "options": {
    "content": "<br>\r\n<p><b>Blocking chains</b> Excessive locking can cause blocking chains. Blocking chains happen when two or more queries are trying to access data that is being locked by the first query. In such case, none of the queries can complete until the first query completes first. Blocking chains often indicate bad indexes, excessive scanning, lock escanation and overall bad application design.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocked Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = MAX([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Processes blocked')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 152 },
   "options": {
    "content": "<br><br><h1 id=\"memory\">SQL Server Memory</h2>\r\n<p>The memory section shows the internals of SQL Server memory and its pressure points.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Physical Memory in use] = AVG([physical_memory_in_use_kb])\n      ,[Available Commit limit] = AVG(available_commit_limit_kb)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_process_memory]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "SQL Memory Breakdown",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Connection Memory (KB)','Optimizer Memory (KB)','SQL Cache Memory (KB)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Total Server Memory (KB)','Stolen Server Memory (KB)', 'Target Server Memory (KB)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [clerk_name]\n      ,[value] = sum([allocated_kb])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_memory_clerks]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [clerk_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 179 },
   "options": {
    "content": "<br>\r\n<p><b>Memory Grants Outstanding</b>: The total number of processes per second that have successfully acquired a workspace memory grant.<br>\r\n<b>Memory Grants Pending </b>: *You want 0*  The total number of processes per second waiting for a workspace memory grant. Numbers higher than 0 indicate a lack of memory.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Grants",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Memory Grants Outstanding','Memory Grants Pending')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 187 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>Free List Stalls/sec</b>: *You want < 2*. Monitors the number of requests per second where data requests stall because no buffers are available. Any value above 2 means SQL Server needs more memory.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Free list stalls/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Free list stalls/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 194 },
   "options": {
    "content": "<br>\r\n<p><b>Page lookups Rate</b>: *You want < 100*  The ratio of *Page lookups/ sec* and *Batch Requests/ sec*. The number of requests to find a page in the buffer pool. When the ratio of batch requests to page lookups crests 100, you may have inefficient execution plans or too many adhoc queries.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Page Lookup Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page Lookups/sec','Batch Requests/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 202 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>Readahead/sec</b>:  *You want < 20% of Page Reads/ sec*   \r\nThe number of data pages read per second in anticipation of their use. If this value is made up even a sizeable minority of total Page Reads/sec (say, greater than 20% of total page reads), you may have too many physical reads occurring.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Readahead pages/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Readahead pages/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 210 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>\r\nPage Reads/sec\r\n</b>:   *You want < 90* The number of physical database page reads issued per second. Normal OLTP workloads support 80 – 90 per second, but higher values may be a yellow flag for poor indexing or insufficient memory.\r\n</p>\r\n\r\n\r\n<p>\r\n<b>Page Writes/sec</b>: *You want < 90* The number of database pages physically written to disk per second. Normal OLTP workloads support 80 – 90 per second. Values over 90 should be crossed checked with \"lazy writer/sec\" and \"checkpoint\" counters. If the other counters are also high, then it may indicate insufficient memory.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Page reads/sec vs Page writes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page reads/sec','Page writes/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 219 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>Readahead Rate</b>: *You want < 20%*   \r\nThe ratio of *Readahead/sec* and *Page Reads/ sec*. \r\nNumber of data pages read per second in anticipation of their use. If this value is makes up even a sizeable minority of total Page Reads/sec (say, greater than 20% of total page reads), you may have too many physical reads occurring.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Readahead rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Readahead pages/sec','Page reads/sec')\n  AND [sql_instance] = '$sql_instance'\n  AND [cntr_value_calculated] > 0\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 227 },
   "options": {
    "content": "<br>\r\n<p><b>Lazy Writes/Sec</b>: *You want< 20*   \r\nMonitors the number of times per second that the Lazy Writer process moves dirty pages from the buffer to disk as it frees up buffer space. Lower is better with zero being ideal. When greater than 20, this counter indicates a need for more memory.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lazy writes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Lazy writes/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 235 },
   "options": {
    "content": "<br>\r\n<p><b>Page Life Expectancy</b> Tells, on average, how many seconds SQL Server expects a data page to stay in cache. The target on an OLTP system should be at least 300 (5 min). When under 300, this may indicate poor index design (leading to increased disk I/O and less effective use of memory) or, simply, a potential shortage of memory. </p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg page life expentancy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page life Expectancy')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 243 },
   "options": {
    "content": "<br>\r\n<p><b>Buffer Cache Hit Ratio</b> Long a stalwart counter used by SQL Server DBAs, this counter is no longer very useful. It monitors the percentage of data requests answer from the buffer cache since the last reboot. However, other counters are much better for showing current memory pressure that this one because it blows the curve. For example, PLE (page life expectancy) might suddenly drop from 2000 to 70, while buffer cache hit ration moves only from 98.2 to 98.1. Only be concerned by this counter if it’s value is regularly below 90 (for OLTP) or 80 (for very large OLAP).\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 246 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Buffer cache hit ratio')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 251 },
   "options": {
    "content": "<br><br><h1 id=\"tempdb\">TempDB</h1>\r\n<p>TempDB is a temporary, and very important database in SQL Server. We, users, can use it by creating temporary tables #table or ##table or even physical tables dbo.table. The tempdb is recreated every time SQL Server starts so we must not be storing anything of value there.\r\nSQL Server heavily relies on tempodb for its query execution - sometime it will use tempdb for sorting data or to \"spill\" data if it runs out of memory or if the query is not optimised. So, when we say \"my query does not use tempdb\" this may not be true.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tempdb Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Active Temp Tables','Temp Tables Creation Rate')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Free space in tempdb",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 261 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = SUM([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Free Space in tempdb (KB)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 266 },
   "options": {
    "content": "<br><br><h1 id=\"storage\">SQL Server Storage</h1>\r\n<p>SQL Server is very fast at handling large volumes of data per CPU core. However, that data has to come from the storage so it is critical that the storage is able to deliver the desired throughput.<br>\r\nYou will want to make sure that the storage interfaces are not saturated and if they are, you will have to look at either upgrading or performance tunning your storage devices. Or, tune your queries to pull less data.</p>\r\n<p>This section shows what SQL Server does with the storage, how much data its reading or writing, how it uses indexes etc...</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes Transferred",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Bytes Written] = SUM([num_of_bytes_written_delta])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Bytes Read] = SUM([num_of_bytes_read_delta])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Bytes written/sec vs Bytes read/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Bytes Written/sec] = AVG([bytes_written_per_second])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Bytes Read/sec] = AVG([bytes_read_per_second])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 281 },
   "options": {
    "content": "<br><p><b>Page Splits/sec</b> :  *You want < 20 per 100 Batch Requests/Sec* - Monitors the number of page splits per second which occur due to overflowing index pages and should be as low as possible. To avoid page splits, review table and index design to reduce non-sequential inserts or implement fill factor and pad_index to leave more empty space per page. NOTE: A high value for this counter is not bad in situations where many new pages are being created since it includes new page allocations.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Page Splits/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 284 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page Splits/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 289 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>\r\nPage Splits Rate:\r\n</b>\r\n*You want < 20 %* Monitors the number of page splits per second which occur due to overflowing index pages and should be as low as possible. To avoid page splits, review table and index design to reduce non-sequential inserts or implement fill factor and pad_index to leave more empty space per page. NOTE: A high value for this counter is not bad in situations where many new pages are being created since it includes new page allocations.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Page Splits Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 292 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Page Splits/sec','Batch Requests/Sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Long IO requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Latency] = SUM([total_long_ios])\n      ,metric=ISNULL([longest_pending_request_file],'')\n  FROM [dbo].[vw_sqlwatch_report_fact_xes_iosubsystem]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) ,[longest_pending_request_file]\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Log Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 304 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Flushes/sec','Log write waits')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 309 },
   "options": {
    "content": "<br>\r\n<p>\r\n<b>Log Flushes/sec</b>: Technically, the number of log pages flushed to the transaction log per second.\r\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 311 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Flushes/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 316 },
   "options": {
    "content": "<p>Making the file physically bigger is an expensive operation for the operating system. If you have a lot of log grows you may consider \"pre-growing\" files manually to a set size.<br>\r\nIn modern OS, you can also look at enablig Instant File Initialization which can grow files at no cost.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Growths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 318 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = SUM([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Growths')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 323 },
   "options": {
    "content": "<br>\r\n<p><b>Full Scans/sec</b>: *You want 1 Full Scan/sec per 1000 Index Searches/sec*. Monitors the number of full scans on tables or indexes. Ignore unless high CPU coincides with high scan rates. High scan rates may be caused by missing indexes, very small tables, or requests for too many records. A sudden increase in this value may indicate a statistics threshold has been reached, resulting in an index no longer being used.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Full Scans /sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 326 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Full Scans/sec','Index Searches/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Full Scan Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 331 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [counter_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Full Scans/sec','Index Searches/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [counter_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 336 },
   "options": {
    "content": "<br><br><h1 id=\"disks\">OS Disks</h1>\r\n<p>In contrast to the section above - SQL Server Storage, this section is related to the OS storage and logical disks presented to the OS<p>\r\n<br>\r\n<p>In OLTP systems the ideal latency is below **8ms** but anything below **20ms** can be acceptable. The latency between **20ms** and **50ms** could lead to performance problems. Latency above **50ms** is likely inadequate if you want a fast database. In the Data Warehouse workload, latencies around **500ms** and more are normal. This is becuase in the Data Warehouse we are often reading a lot of data at once and saturate the storage IO whereas in OLTP systems we are making a lot of small writes and reads and therefore storage must be very responsive.</p>\r\n\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logical disk latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 343 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,[Latency] = MAX([io_latency_read])+MAX([io_latency_write])\n      ,metric=left([file_physical_name],1)\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([snapshot_time], $aggregation) , left([file_physical_name],1)\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Physical File Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 348 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = MAX([io_latency_write])\n      ,metric=file_physical_name\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name\nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = MAX([io_latency_read])\n      ,metric=file_physical_name\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Physical File Transfers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 353 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = SUM([num_of_bytes_written_delta])\n      ,metric=file_physical_name + ' (Writes)'\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name + ' (Writes)'\nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = SUM([num_of_bytes_read_delta])\n      ,metric=file_physical_name + ' (Reads)'\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name + ' (Reads)'\n \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 358 },
   "options": {
    "content": "<br><br><h1 id=\"network\">OS Network</h1>\r\n<p>Network interfaces exposed to the OS. Any network traffic from and to SQL Server will be going through these.</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network IO waits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 362 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([snapshot_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name = 'Network IO waits'\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([snapshot_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  }
 ]
}