{
 "title": "Long Queries",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-10m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   { "name": "LongQueryId", "label": "Long Query Id" }
  ]
 },
 "panels": [
  {
   "title": "Long Queries over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT [time]= d.event_time, [Long queries] = count(distinct d.session_id)\n  FROM dbo.sqlwatch_logger_snapshot_header h\n    inner join [dbo].[sqlwatch_logger_xes_long_queries] d\n\t\ton  h.snapshot_time = d.[snapshot_time]\n\t\tand h.snapshot_type_id = d.snapshot_type_id\n\t\tand h.sql_instance = d.sql_instance\n  WHERE h.snapshot_type_id = 7\n     AND h.[sql_instance] = '$sql_instance'\n   AND $__timeFilter(d.event_time)\n   GROUP BY d.event_time\nORDER BY\n  d.event_time desc"
    }
   ]
  },
  {
   "title": "Long Queries Details",
   "type": "table",
   "description": "Click on the row or long_query_id column to display SQL Text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT d.*\n  FROM dbo.sqlwatch_logger_snapshot_header h\n    inner join [dbo].[sqlwatch_logger_xes_long_queries] d\n\t\ton  h.snapshot_time = d.[snapshot_time]\n\t\tand h.snapshot_type_id = d.snapshot_type_id\n\t\tand h.sql_instance = d.sql_instance\n  WHERE h.snapshot_type_id = 7\n     AND h.[sql_instance] = '$sql_instance'\n   AND $__timeFilter(d.event_time)\nORDER BY\n  event_time desc"
    }
   ]
  },
  {
   "title": "Query Text",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT time=getdate(),d.sql_text, d.statement\n  FROM dbo.sqlwatch_logger_snapshot_header h\n    inner join [dbo].[sqlwatch_logger_xes_long_queries] d\n\t\ton  h.snapshot_time = d.[snapshot_time]\n\t\tand h.snapshot_type_id = d.snapshot_type_id\n\t\tand h.sql_instance = d.sql_instance\n  WHERE h.snapshot_type_id = 7\n     AND h.[sql_instance] = '$sql_instance'\n   AND long_query_id = isnull('$LongQueryId',-1)\n"
    }
   ]
  }
 ]
}