{
 "title": "Wait Events",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "1s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Waits", "label": "Group Waits By", "query": "Category,Type" },
   {
    "name": "WaitType",
    "label": "Wait Type",
    "query": "select distinct wc.wait_type from  [dbo].[sqlwatch_logger_xes_wait_event] ws\n  inner join dbo.vw_sqlwatch_meta_wait_stats_category wc on wc.wait_type_id = ws.wait_type_id where $__timeFilter(event_time)"
   },
   {
    "name": "DetailWaitTypes",
    "label": "DetailWaitTypes",
    "query": "select distinct wc.wait_type from  [dbo].[sqlwatch_logger_xes_wait_event] ws\n  inner join dbo.vw_sqlwatch_meta_wait_stats_category wc on wc.wait_type_id = ws.wait_type_id where $__timeFilter(event_time)"
   },
   { "name": "DetailWaitTime", "label": "Filter Wait Time", "query": "1970-01-01" },
   {
    "name": "Database",
    "label": "Database",
    "query": "select distinct database_name \nfrom [dbo].[vw_sqlwatch_report_fact_xes_wait_events] \nwhere [sql_instance] = '$sql_instance'\nand $__timeFilter(event_time)"
   },
   { "name": "SQLHandle", "label": "SQL Handle" },
   { "name": "SQLText", "label": "SQL Text" },
   { "name": "QueryHash", "label": "Query Hash" }
  ]
 },
 "panels": [
  {
   "title": "Wait Events",
   "type": "graph",
   "description": "Events with wait longer than 1 second as registered by the Extended Event Session. \n\nPlease note that the fact that the query is waiting for a resource, does not mean that it is the query's fault. It could be a dozen of other \"heavy\" queries causing this particular query to wait. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time]= $__timeGroup([event_time], $aggregation) \n      ,metric = case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,[value] = sum([duration])\n  FROM [vw_sqlwatch_report_fact_xes_wait_events]\n    \n  WHERE $__timeFilter(event_time)\n  AND [sql_instance] = '$sql_instance'\n  and wait_type in ($WaitType)\n  and [text] like case when '$SQLText' <> '' then '%$SQLText%' else '%' end \n  and database_name in ($Database)\nGROUP BY $__timeGroup([event_time], $aggregation) ,\ncase when '$Waits' = 'Category' then [wait_category] else [wait_type] end\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \t event_time\t\n\t\t,statement\n\t,wait_type\t\n\t,wait_category\t\n\t,activity_id = convert(varchar(36),activity_id)\t\n\t,activity_id_sequence\t\n\t,duration\t\n\t,signal_duration\t\n\t,session_id\t\n\t,username\t\n\t,client_hostname\t\n\t,client_app_name\t\n\t,database_name\t\n\t,sql_instance\t\n\t,snapshot_time\t\n\t,snapshot_type_id\n\t,sql_handle = '--'+convert(nvarchar(64),sql_handle,1)\n\t,query_hash = '--'+convert(nvarchar(64),query_hash)\nfrom [dbo].[vw_sqlwatch_report_fact_xes_wait_events] \nWHERE [sql_instance] = '$sql_instance'\n  and (wait_type in ($DetailWaitTypes) or wait_category in ($DetailWaitTypes))\n  and [text] like case when '$SQLText' <> '' then '%$SQLText%' else '%' end\n  and DATEADD(SECOND,$__timeGroup([event_time], $aggregation),'1970-01-01') = '$DetailWaitTime'"
    }
   ]
  },
  {
   "title": "SQL Text",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n      [time]=GETUTCDATE() \n      ,metric = text\n      ,[value] = 1\n  FROM [dbo].[sqlwatch_meta_sql_text]\n  WHERE 1=1 --$__timeFilter(snapshot_time)\n  and sql_handle = convert(varbinary(64),replace('$SQLHandle','--',''),1)\n  AND [sql_instance] = '$sql_instance'\n  \n  "
    }
   ]
  },
  {
   "title": "Average Query Wait Duration History",
   "type": "graph",
   "description": "Based on the Query Hash in the Wait Event History",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n      [time]= [event_time] --$__timeGroup([event_time], $aggregation) \n      ,metric = case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n      ,[value] = [duration] --avg([duration])\n  FROM [dbo].[vw_sqlwatch_report_fact_xes_wait_events]\n  WHERE 1=1--$__timeFilter(snapshot_time)\n  AND query_hash = convert(varchar(64),replace('$QueryHash','--',''),1)\n  AND [sql_instance] = '$sql_instance'\n  \n  --GROUP BY case when '$Waits' = 'Category' then [wait_category] else [wait_type] end\n    --  ,$__timeGroup([event_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  }
 ]
}