{
 "title": "Data Files",
 "tags": [ "SQLWATCH" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "mssql" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": "SELECT [servername] FROM [dbo].[sqlwatch_meta_server]"
   },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Physical File Latency",
   "type": "graph",
   "description": "In OLTP systems the ideal latency is below **8ms** but anything below **20ms** can be acceptable. The latency between **20ms** and **50ms** could lead to performance problems. Latency above **50ms** is likely inadequate if you want a fast database. \n\nIn the Data Warehouse workload, latencies around **500ms** and more are normal. This is becuase in the Data Warehouse we are often reading a lot of data at once and saturate the storage IO whereas in OLTP systems we are making a lot of small writes and reads and therefore storage must be very responsive.",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = MAX([io_latency_write])\n      ,metric=file_physical_name\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name\nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = MAX([io_latency_read])\n      ,metric=file_physical_name\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name\nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Database Transactions /sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = [instance_name]\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Transactions/sec')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY [instance_name]\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Log Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Flushes/sec','Log write waits')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Tempdb Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = AVG([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Active Temp Tables','Temp Tables Creation Rate')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Physical File Transfers",
   "type": "graph",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = SUM([num_of_bytes_written_delta])\n      ,metric=file_physical_name + ' (Writes)'\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name + ' (Writes)'\nORDER BY\n  time ASC\n  \n  "
    },
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,[Latency] = SUM([num_of_bytes_read_delta])\n      ,metric=file_physical_name + ' (Reads)'\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_file_stats]\n  WHERE 1 = 1\n  AND $__timeFilter(snapshot_time)\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY $__timeGroup([report_time], $aggregation) , file_physical_name + ' (Reads)'\n \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Free space in tempdb",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = SUM([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Free Space in tempdb (KB)')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  },
  {
   "title": "Log Growths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n      [time] = $__timeGroup([report_time], $aggregation) \n      ,metric = counter_name\n      ,[value] = SUM([cntr_value_calculated])\n  FROM [dbo].[vw_sqlwatch_report_fact_perf_os_performance_counters]\n  WHERE [aggregation_interval_minutes] = 1\n  AND $__timeFilter(snapshot_time)\n  AND counter_name IN ('Log Growths')\n  AND [sql_instance] = '$sql_instance'\n  GROUP BY counter_name\n      ,$__timeGroup([report_time], $aggregation) \nORDER BY\n  time ASC\n  \n  "
    }
   ]
  }
 ]
}