CREATE TABLE [dbo].[sqlwatch_logger_xes_long_queries](
	--[long_query_id] bigint identity (-9223372036854775808,1),
	[activity_id] int identity(1,1),
	[activity_sequence] smallint,
	[activity_id_xfer] uniqueidentifier,
	[activity_seqeuence_xfer] smallint,
	--[event_time_start] datetime not null,
	[event_time] [datetime] not null,
	[event_name] [varchar](255) not null,
	[session_id] [bigint] not null,
	[database_name] [varchar](255) NULL,
	[cpu_time] [bigint] NULL,
	[physical_reads] [bigint] NULL,
	[logical_reads] [bigint] NULL,
	[writes] [bigint] NULL,
	[spills] [bigint] NULL,
	[offset] [bigint] NULL,
	[offset_end] [bigint] NULL,
	[statement] [varchar](max) NULL,
	[username] [varchar](255) NULL,
	[sql_text] [varchar](max) NULL,
	[object_name] [varchar](max) NULL,
	[client_hostname] [varchar](255) NULL,
	[client_app_name] [varchar](255) NULL,
	[duration_ms] [bigint] NULL,
	[wait_type] [varchar](255) NULL,
	--[blocking_report] [xml] NULL,
	--[deadlock_report] [xml] NULL,
	[snapshot_time] datetime not null,
	[snapshot_type_id] tinyint not null default 7,
	[sql_instance] nvarchar(25) not null default @@SERVERNAME,
	constraint fk_logger_perf_xes_long_queries foreign key ([snapshot_time],[snapshot_type_id],[sql_instance]) references [dbo].[sqlwatch_logger_snapshot_header]([snapshot_time],[snapshot_type_id],[sql_instance]) on delete cascade  on update cascade,
	constraint pk_logger_perf_xes_long_queries primary key nonclustered (
		[snapshot_time], [snapshot_type_id], [activity_id], [activity_sequence],[sql_instance]
	),
	constraint fk_sqlwatch_logger_xes_long_queries_server foreign key ([sql_instance])
		references [dbo].[sqlwatch_meta_server] ([sql_instance]) on delete cascade
) ON [PRIMARY] 
